### ISSUE TITLE
Something is causing taint

### ISSUE THREAD

**Issue by sbaildon** [sbaildon/sInterface#16]
Probably the ObjectTracker frame logic
/console taintLog 1

**Comment by sBaildon** [comment]
https://gist.github.com/sBaildon/25c1472e6aa29cd44a0a3142f390df60

**Comment by sBaildon** [comment]
Partially fixed by: https://github.com/sBaildon/sInterface/commit/867d1b3308148f48751982b50e20d0ca7776937b
