### ISSUE TITLE
curse/wowinterface/wowace releases

### ISSUE THREAD

**Issue by sbaildon** [sbaildon/sInterface#21]
pkgmeta or whatever

**Comment by sBaildon** [comment]
Support for automated releases merged in https://github.com/sBaildon/sInterface/commit/860b2f1175157d37a67cdcce3ea73424035d4ee4

**Comment by sBaildon** [comment]
WoWinterface release is pending approval

**Comment by sbaildon** [comment]
wowinterface release is done

**Comment by sbaildon** [comment]
will reopen if I decide to target curse. won't be doing that for now.
