### ISSUE TITLE
feature request: actionbar icon frames

### ISSUE THREAD

**Issue by apricant** [sBaildon/sInterface#27]
I'm not sure if it's possible, but would one be able to easily add support for custom frames around skill/spell icons in the actionbar that match the design language of sInterface? would this cause much bloat and defeat the purpose behind sInterface?

**Comment by sBaildon** [comment]
It's something I've always intended, but because I play with action bars hidden it's been on the back-burner. I'll (hopefully) give it a look soon

**Comment by sBaildon** [comment]
Tracking here: https://github.com/sBaildon/sInterface/tree/actionbutton_styler
