### ISSUE TITLE
bug: unitframes in release 0.9.2

### ISSUE THREAD

**Issue by apricant** [sBaildon/sInterface#28]
finding that default Blizz UF UI is in the corner as it is by default, I'm running a retail copy via wine, but was able to reproduce this behavior on Windows as well. All other addons are disabled and the game is newly installed with a fresh WTF. I was able to fix it by rolling back to 0.9.1 but keeping the Details skin from the latest release.

**Comment by sBaildon** [comment]
Might've been related to a bad reference to oUF.

After a clean windows installation I found that the submodule commit reference wasn't visible. Should be fixed now

**Comment by apricant** [comment]
solid, thanks, I just reinstalled windows so I'll give it a test tonight

**Comment by apricant** [comment]
works as expected! closing

**Comment by apricant** [comment]
unfortunately experiencing this again after latest release, only addons installed are sinterface and details with a newly generated WTF and Cache

**Comment by apricant** [comment]
from v0.10.1

![Image of unitframe bug](https://a.doko.moe/uijmrq.jpg)

**Comment by sBaildon** [comment]
Caught it after a fresh download—bad config option. Fixed here: https://github.com/sBaildon/sInterface/commit/cda890d04ca243cf2275533750f7fce0be2a1bd6

v0.10.2 is building on travis right now

**Comment by apricant** [comment]
Much thanks! Looked at the changes, not sure if I'd have caught that!
