### ISSUE TITLE
errors LUA

### ISSUE THREAD

**Issue by kitaro2003** [sBaildon/sInterface#35]
Message: ...nterface\AddOns\sInterface\modules\skins\details.lua:121: attempt to index global 'Details' (a nil value)
Time: 06/11/18 15:13:20
Count: 1
Stack: ...nterface\AddOns\sInterface\modules\skins\details.lua:121: attempt to index global 'Details' (a nil value)
[C]: ?
...nterface\AddOns\sInterface\modules\skins\details.lua:121: in function <...nterface\AddOns\sInterface\modules\skins\details.lua:119>

Locals:

**Comment by kitaro2003** [comment]
![wowscrnshot_061118_151605](https://user-images.githubusercontent.com/20854352/41231028-77d9f1d0-6d8a-11e8-92e9-881b7612a50b.jpg)

**Comment by sBaildon** [comment]
I left a response over at WoWInterface http://www.wowinterface.com/downloads/info24674-sInterface.html

New release available here https://github.com/sBaildon/sInterface/releases/tag/v0.11.1

Thanks for pointing this out!

**Comment by sBaildon** [comment]
Fixed by https://github.com/sBaildon/sInterface/commit/32f5e392823c2528557c65de1d50dc6f47371dfc
