### ISSUE TITLE
Border blinking when comparing an item.

### ISSUE THREAD

**Issue by Dools1337** [sbaildon/sInterface#55]
Hey!

I'm using your tooltip and it looks like there is a bug when comparing items. Not quite sure what would be the cause of it. 
See .gif : 

![Blinking borders](https://media.giphy.com/media/kqOqMfMMXzjXbvHOGr/giphy.gif)

Not sure if it's clashing with another addon that touches the tooltip frame. Pretty sure it wasn't there before 9.0.1 
Any idea ?

**Comment by sbaildon** [comment]
I've caught this myself, and I'm fairly confident I know why it's happening. No conflict, just some bad code.

I'll see what I can do

**Comment by sbaildon** [comment]
Got it. Thank you :-)

**Comment by Dools1337** [comment]
Ah I got excited for a moment but look : 

![Blinking borders](https://media.giphy.com/media/jdvl8CkkZI4JoEc8W0/giphy.gif)

Tbh maybe it's an issue on my end, completely possible. 

You can see the  blinking border is " styled " now.
